before_install:
- gem install travis -v 1.8.8
- travis login --org --github-token $GITHUB_TOKEN
- travis whoami
- travis env copy OPENSSL_IV OPENSSL_KEY --repo just-containers/PRoot
- travis env copy OPENSSL_IV OPENSSL_KEY --repo just-containers/qemu
- travis env copy OPENSSL_IV OPENSSL_KEY --repo just-containers/musl-cross-make
- travis env copy OPENSSL_IV OPENSSL_KEY --repo just-containers/skaware
- travis env copy OPENSSL_IV OPENSSL_KEY --repo just-containers/busybox-chroots
- travis env copy OPENSSL_IV OPENSSL_KEY --repo just-containers/socklog-overlay
- travis env copy OPENSSL_IV OPENSSL_KEY --repo just-containers/socklog-static
- travis env copy OPENSSL_IV OPENSSL_KEY --repo just-containers/socklog
- bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.before_install
install:
- bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.install
script:
- bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.script
after_success:
- bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.after_success
